#!/bin/sh
set -e

find /var/db/repos/localrepo -name '*.ebuild' -type f -exec ebuild {} manifest \;

GENPACK_PROGS_DIR=/var/cache/repos/genpack-progs

if [ -d $GENPACK_PROGS_DIR/.git ]; then
        git -C $GENPACK_PROGS_DIR pull || echo "Failed accessing git. Proceedeng with present source..."
else
        git clone https://github.com/wbrxcorp/genpack-progs.git /var/cache/repos/genpack-progs
fi
(cd $GENPACK_PROGS_DIR && make && make install)

build-kernel --config /kernel-config.`uname -m`

emerge -uDN -bk --binpkg-respect-use=y --exclude='sys-kernel/*' world @all

g++ -std=c++2a -static-libgcc -static-libstdc++ -o /init /init.cpp /init-overrides.cpp -lmount -lblkid -liniparser4
rm -f /boot/initramfs
/init > /boot/initramfs

mkdir -p /var/cache/repos

if [ -d /var/cache/repos/wghub ]; then
	cd /var/cache/repos/wghub
	git pull
else
	git clone  https://github.com/shimarin/wghub.git /var/cache/repos/wghub
	cd /var/cache/repos/wghub
fi
make libwghub.a
make install

