#!/bin/sh
set -e
VERSION=`file -L /boot/kernel| sed 's/^.\+ version \([^ ]\+\)\s.\+$/\1/'|sed 's/-gentoo//'`
sed -i "s/__VERSION__/$VERSION/g" /boot/grub/grub.cfg

touch /usr/sbin/install-system-image
touch /usr/sbin//expand-rw-layer
touch /usr/sbin/do-with-lvm-snapshot
touch /usr/sbin/rpmbootstrap
touch /usr/sbin/genbootstrap

systemctl enable mdmonitor zram_swap terminal

