#!/bin/sh
set -e

download http://mirrors.jenkins.io/war/latest/jenkins.war > /opt/jenkins/jenkins.war
sed -i 's/^Type=forking$/Type=simple/' /lib/systemd/system/jenkins.service #https://github.com/jenkinsci/jenkins/pull/5561

sed -i 's/^JENKINS_ENABLE_ACCESS_LOG=.*$/JENKINS_ENABLE_ACCESS_LOG="yes"/' /etc/conf.d/jenkins
sed -i 's/^\(jenkins:.\+:\)\/sbin\/nologin$/\1\/bin\/bash/' /etc/passwd
mkdir /var/lib/jenkins/.ssh
chmod 700 /var/lib/jenkins/.ssh
touch /var/lib/jenkins/.ssh/authorized_keys
echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > /var/lib/jenkins/.ssh/config
chown -R jenkins.jenkins /var/lib/jenkins/.ssh

#$require chromium.lst
#$require xvfb.lst
#$require fluxbox.lst

download https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb > /tmp/chrome.deb

echo -e '*nat\n-A PREROUTING -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080\nCOMMIT' > /var/lib/iptables/rules-save
echo -e '*nat\n-A PREROUTING -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080\nCOMMIT' > /var/lib/ip6tables/rules-save
