#!/bin/sh
set -e

# setup database
cat << 'EOS' > /tmp/sql
create database `nextcloud`;
create user `nextcloud`@localhost;
grant all privileges on `nextcloud`.* to `nextcloud`@localhost;
EOS

with-mysql 'mysql -u root < /tmp/sql'

# setup PHP
if [ -d /opt/remi/php74 ]; then
	systemctl enable php74-php-fpm
	PHP_INI=/etc/opt/remi/php74/php.ini
elif [ -d /opt/remi/php80 ]; then
	systemctl enable php80-php-fpm
	PHP_INI=/etc/opt/remi/php80/php.ini
else
	download https://pecl.php.net/get/smbclient > /tmp/smbclient.tgz
	pecl install /tmp/smbclient.tgz

	PHP_CLI_DIR=/etc/php/cli-`eselect php show cli`
	PHP_APACHE2_DIR=/etc/php/apache2-`eselect php show apache2`

	echo "extension=smbclient.so" > $PHP_CLI_DIR/ext/smbclient.ini
	echo "extension=smbclient.so" > $PHP_APACHE2_DIR/ext/smbclient.ini

	ln -s ../ext/smbclient.ini $PHP_CLI_DIR/ext-active/smbclient.ini
	ln -s ../ext/smbclient.ini $PHP_APACHE2_DIR/ext-active/smbclient.ini
	PHP_INI=/etc/php/*/php.ini
fi

sed -i 's/^upload_max_filesize.\+$/upload_max_filesize = 512M/' $PHP_INI
sed -i 's/^post_max_size.\+$/post_max_size = 768M/' $PHP_INI
sed -i 's/^memory_limit.\+$/memory_limit=512M/' $PHP_INI
sed -i 's/^;mbstring.func_overload.\+$/mbstring.func_overload=0/' $PHP_INI
sed -i 's/^;always_populate_raw_post_data.\+$/always_populate_raw_post_data=-1/' $PHP_INI
sed -i 's/^;default_charset.\+$/default_charset="UTF-8"/' $PHP_INI

# download nextcloud
echo "Extrtacting Nextcloud..."
if [ "$VARIANT" = "" ]; then
	TARBALL=latest.tar.bz2
else
	TARBALL=latest-$VARIANT.tar.bz2
fi

download https://download.nextcloud.com/server/releases/$TARBALL | tar jxf - --strip-components=1 -C /var/www/localhost/htdocs

mkdir /var/lib/nextcloud
chown -R apache:apache /var/www/localhost /var/lib/nextcloud

# occ command
gcc -o /usr/bin/occ /usr/src/occ/occ.c

mkdir -p /.genpack
#php -r 'include "/var/www/localhost/htdocs/version.php";echo $OC_VersionString;' > /.genpack/nextcloud-version

