#!/bin/sh
set -e

GENPACK_PROGS_DIR=/var/cache/repos/genpack-progs

if [ -d $GENPACK_PROGS_DIR/.git ]; then
        git -C $GENPACK_PROGS_DIR pull || echo "Failed accessing git. Proceedeng with present source..."
else
        git clone https://github.com/wbrxcorp/genpack-progs.git /var/cache/repos/genpack-progs
fi
(cd $GENPACK_PROGS_DIR && make && make install)

build-kernel

emerge -uDN -bk --binpkg-respect-use=y pixman # needed by xen-tools
emerge -uDN -bk --binpkg-respect-use=y --exclude='sys-kernel/*' --buildpkg-exclude='www-servers/apache' world @all

