#!/bin/sh
set -e

recursive_touch() {
        if [ -L $1 ]; then
                TARGET=`readlink $1`
                if [ "${TARGET:0:1}" = "/" ]; then
                        ABS_TARGET=$TARGET
                else
                        ABS_TARGET=`dirname $1`/$TARGET
                fi
                recursive_touch "$ABS_TARGET"
        fi
        touch -h $1
}

touch /linuxrc
recursive_touch /bin/gunzip
recursive_touch /usr/bin/ar

# llmnrd
mkdir -p /tmp/llmnrd
download https://github.com/tklauser/llmnrd/archive/refs/tags/v0.7.tar.gz > /tmp/llmnrd.tar.gz
tar xf /tmp/llmnrd.tar.gz --strip-components=1 -C /tmp/llmnrd
cd /tmp/llmnrd
gcc -static -o /sbin/llmnrd -DVERSION_STRING="\"v`egrep '^VERSION = ' Makefile | sed 's/.*= //'`\"" -DGIT_VERSION='""' -DPIDFILE='"/run/llmnrd.pid"' llmnr.c iface.c socket.c util.c log.c llmnrd.c

g++ -I /usr/include/libxml2 -std=c++20 -D__USE_REAL_MAIN__ -o /usr/bin/rpmbootstrap /usr/src/rpmbootstrap.cpp -lxml2 -lcurl

