#!/bin/sh
set -e

recursive-touch /bin/gunzip /usr/bin/ar

# llmnrd
mkdir -p /tmp/llmnrd
download https://github.com/tklauser/llmnrd/archive/refs/tags/v0.7.tar.gz > /tmp/llmnrd.tar.gz
tar xf /tmp/llmnrd.tar.gz --strip-components=1 -C /tmp/llmnrd
cd /tmp/llmnrd
gcc -static -o /usr/bin/llmnrd -DVERSION_STRING="\"v`egrep '^VERSION = ' Makefile | sed 's/.*= //'`\"" -DGIT_VERSION='""' -DPIDFILE='"/run/llmnrd.pid"' llmnr.c iface.c socket.c util.c log.c llmnrd.c

g++ -I /usr/include/libxml2 -std=c++20 -D__USE_REAL_MAIN__ -o /usr/bin/rpmbootstrap /usr/src/rpmbootstrap.cpp -lxml2 -lcurl
