#!/bin/sh
cd $HOME

if egrep -q '( |^)systemd\.unit=installer\.target( |$)' /proc/cmdline; then
	exec /usr/sbin/wb installer
fi

#else
if [ `cut -f 2,3 -d ' ' /proc/mounts | egrep '^\/run\/initramfs\/rw' | cut -f 2 -d ' '` == "tmpfs" ]; then
	exec /usr/bin/weston-terminal
fi

#else

exec /usr/sbin/wb login

