#!/bin/sh
XDG_RUNTIME_DIR=/run/weston
TTY=1

export XDG_RUNTIME_DIR

if [ -d /proc/xen ]; then
	LANG=ja_JP.utf8
	SHELL=/usr/sbin/textui
	export SHELL LANG
	exec /usr/bin/weston-terminal
fi

#else

if egrep -q '( |^)systemd\.unit=installer\.target( |$)' /proc/cmdline; then
	exec /usr/sbin/wb login --installer tty$TTY
else
	exec /usr/sbin/wb login tty$TTY
fi

