#!/bin/sh
set -e

HUGINN_HOME=/home/huginn

git clone --depth=1 https://github.com/cantino/huginn $HUGINN_HOME
cd $HUGINN_HOME
#gem install rake -v 13.0.6 --no-document
#gem install debug_inspector -v 0.0.3 --no-document
#gem install msgpack -v 1.4.2 --no-document
#gem install bootsnap -v 1.9.3 --no-document
#gem install byebug -v 8.2.5 --no-document
#gem install unf_ext -v 0.0.7.4 --no-document
#gem install eventmachine -v 1.2.7 --no-document
#gem install ffi -v 1.12.2 --no-document
#gem install kgio -v 2.10.0 --no-document
#gem install libv8-node --no-document
# https://github.com/rubyjs/mini_racer/issues/250
#ln -s x86_64-linux-musl /usr/local/lib64/ruby/gems/*/gems/libv8-node-*-x86_64-linux-musl/vendor/v8/x86_64-linux
#gem install --ignore-dependencies mini_racer -v 0.6.2 --no-document
#gem install mysql2 -v 0.5.2 --no-document
#gem install raindrops -v 0.17.0 --no-document
#gem install sassc -v 2.3.0 --no-document
#gem install unicorn -v 5.1.0 --no-document
#gem install nokogiri -v 1.12.5 --no-document
#gem install loofah -v 2.13.0 --no-document
#gem install binding_of_caller -v 0.8.0 --no-document
#gem install kaminari-actionview -v 1.1.1 --no-document
#gem install kaminari -v 1.1.1 --no-document
#gem install rails -v 6.0.4.4 -N # contains actioncable,actionmailbox,actionmailer,actiontext,railties

mv .env.example .env
sed -i 's/^DOMAIN=.*/DOMAIN=/' .env
sed -i 's/^DATABASE_NAME=.*/DATABASE_NAME=huginn/' .env
sed -i 's/^DATABASE_USERNAME=.*/DATABASE_USERNAME=huginn/' .env
sed -i 's/^DATABASE_PASSWORD=.*/DATABASE_PASSWORD=huginn/' .env
sed -i 's/^# RAILS_ENV=production/RAILS_ENV=production/' .env
echo 'RAILS_SERVE_STATIC_FILES=true' >> .env

bundle install
bundler # needs .env file
#grep -v libv8-node Gemfile.lock > /tmp/Gemfile.lock && mv /tmp/Gemfile.lock ./

cat << 'EOS' > /tmp/sql
create database `huginn` charset utf8mb4;
create user `huginn`@localhost identified by 'huginn';
grant all privileges on `huginn`.* to `huginn`@localhost;
EOS
with-mysql 'mysql -u root < /tmp/sql'

cat << 'EOS' > /tmp/patch
diff --git a/config/application.rb b/config/application.rb
index 094aec2f..66fc3e35 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -47,5 +47,7 @@ module Huginn

     config.action_view.sanitized_allowed_tags = %w[strong em b i p code pre tt samp kbd var sub sup dfn cite big small address hr br div span h1 h2 h3 h4 h5 h6 ul ol li dl dt dd abbr acronym a img blockquote del ins style table thead tbody tr th td]
     config.action_view.sanitized_allowed_attributes = %w[href src width height alt cite datetime title class name xml:lang abbr border cellspacing cellpadding valign style]
+
+    config.middleware.delete ActionDispatch::HostAuthorization
   end
 end
EOS
#patch -p1 < /tmp/patch

useradd huginn
passwd -d huginn
chown -R huginn.huginn $HUGINN_HOME

systemctl enable huginn
