#!/bin/sh
set -e

GENPACK_PROGS_DIR=/var/cache/repos/genpack-progs

if [ -d $GENPACK_PROGS_DIR/.git ]; then
        git -C $GENPACK_PROGS_DIR pull || echo "Failed accessing git. Proceedeng with present source..."
else
        git clone https://github.com/wbrxcorp/genpack-progs.git /var/cache/repos/genpack-progs
fi
(cd $GENPACK_PROGS_DIR && make && make install)

# ensure there kernel configs
# CONFIG_DEFAULT_INIT="/sbin/overlay-init"
# CONFIG_VIRTIO_BLK=y
# CONFIG_SQUASHFS=y
# CONFIG_SQUASHFS_XZ=y
# !CONFIG_MODULE_SIG_ALL=y
# !CONFIG_EFI_ZBOOT=y

emerge -uDN -bk --binpkg-respect-use=y world @all eclean-kernel

eclean-kernel -n 1 || true

cd /boot
ln -sf kernel-* kernel
