#!/bin/sh
set -e

GENPACK_OVERLAY=/var/cache/repos/genpack-overlay

if [ -d $GENPACK_OVERLAY/.git ]; then
        git -C $GENPACK_OVERLAY pull || echo "Failed accessing git. Proceedeng with present source..."
else
        git clone https://github.com/wbrxcorp/genpack-overlay.git $GENPACK_OVERLAY
fi
if [ ! -f /etc/portage/repos.conf/genpack-overlay.conf ]; then
	mkdir -p /etc/portage/repos.conf
	echo -e '[genpack-overlay]\nlocation=/var/cache/repos/genpack-overlay' > /etc/portage/repos.conf/genpack-overlay.conf
fi

# ensure there kernel configs
# CONFIG_DEFAULT_INIT="/sbin/overlay-init"
# CONFIG_VIRTIO_BLK=y
# CONFIG_SQUASHFS=y
# CONFIG_SQUASHFS_XZ=y
# !CONFIG_MODULE_SIG_ALL=y
# !CONFIG_EFI_ZBOOT=y

emerge -uDN -bk --binpkg-respect-use=y world @all eclean-kernel

eclean-kernel -n 1 || true

cd /boot
ln -sf kernel-* kernel
